Repository solipr/solipr, pull requests merged in 2024-10, with the labels that each got.

#8 Use rust nightly by default to use latest features
  .cargo/config.toml
  .github/workflows/rust.yml
  Cargo.lock
  rust-toolchain.toml
Labels: enhancement

#9 Stack vector implementation
  src/lib.rs
  src/stack.rs
Labels: enhancement

#10 Fix the deprecated rustfmt version tag
  rustfmt.toml
Labels: invalid

#13 Adding a name to the GitHub Action
  .github/workflows/rust.yml
Labels: bug, enhancement

#14 Derive Copy for stack::Vec
  src/stack.rs
Labels: enhancement

#12 Ignore useless files in helix file picker
  .ignore
Labels: enhancement

#16 Remove useless commands in devcontainer
  .devcontainer/Dockerfile
  .devcontainer/devcontainer.json
Labels: enhancement

#17 Allow using the module name for struct
  Cargo.toml
  src/stack.rs
Labels: enhancement

#15 Add simple trait to represent the content registry
  Cargo.lock
  Cargo.toml
  src/lib.rs
  src/registry.rs
Labels: enhancement

#24 Update the registry trait to add atomic transactions
  src/registry.rs
Labels: enhancement

#22 Async serialization and deserialization system
  Cargo.toml
  src/lib.rs
  src/serializer.rs
  src/stack.rs
Labels: enhancement

#21 Basic structure of a Change in a repository
  Cargo.lock
  Cargo.toml
  src/change.rs
  src/lib.rs
Labels: enhancement

#26 Make registry tags more generic
  src/registry.rs
Labels: enhancement

#28 Make the registry a lot simpler
  src/registry.rs
Labels: enhancement

#30 Stop using alloc external crate
  Cargo.toml
Labels: enhancement

#31 Remove async code and convert it to sync code
  Cargo.lock
  Cargo.toml
  src/registry.rs
Labels: enhancement

#32 Make Change hashable
  Cargo.lock
  Cargo.toml
  src/change.rs
  src/registry.rs
  src/stack.rs
Labels: enhancement

#36 Define RepositoryManager and Repository trait
  Cargo.toml
  src/lib.rs
  src/repository.rs
Labels: enhancement

#37 Remove impl_trait_in_params lint
  Cargo.toml
Labels: enhancement

#38 Make ChangeHash not depend on ContentHash
  Cargo.lock
  src/change.rs
  src/registry.rs
Labels: enhancement

#39 Making Hash and identifiers implement Debug and Display
  Cargo.lock
  Cargo.toml
  src/change.rs
  src/registry.rs
  src/repository.rs
Labels: enhancement

#40 Stop using core instead of std
  Cargo.toml
  src/change.rs
  src/registry.rs
  src/repository.rs
  src/stack.rs
Labels: enhancement

#41 Stop putting inline to each functions
  Cargo.toml
  src/change.rs
  src/registry.rs
  src/repository.rs
  src/stack.rs
Labels: enhancement

#42 Make itering over the changes returns the value
  src/repository.rs
Labels: enhancement

#43 Make identifiers sortable
  src/change.rs
  src/repository.rs
Labels: enhancement

#44 Make apply to a Repository return the hash
  src/repository.rs
Labels: enhancement

#45 Edit repository take a mutable reference
  src/repository.rs
Labels: enhancement

#46 Allow clippy::multiple_crate_versions lint
  Cargo.toml
Labels: enhancement

#49 Add memory implementation of registry
  src/registry.rs
  src/registry/memory.rs
Labels: enhancement

#47 Implement a persistent repository
  Cargo.lock
  Cargo.toml
  src/repository.rs
  src/repository/persistent.rs
Labels: enhancement

#51 Add new logo
  logo.svg
Labels: enhancement

#52 Add background logo and organize
  README.md
  logo/logo-background.png
  logo/logo-background.svg
  logo/logo.png
  logo/logo.svg
Labels: enhancement

#54 Add large version of the logo
  logo/logo-large.png
  logo/logo-large.svg
Labels: documentation, enhancement

#55 Implement a persistant version of the registry
  src/registry.rs
  src/registry/persistent.rs
Labels: enhancement

#56 Change the link to Tipragot's profile
  README.md
Labels: documentation

#58 Adding a way to get all existing line in a file
  src/repository.rs
Labels: enhancement

#57 Store the dependent changes to make removing a change to a persistent repository faster
  src/repository/persistent.rs
Labels: enhancement

#60 Implement rendering a file to a graph
  src/repository.rs
Labels: enhancement

#66 Add `new` function to `Registry` implementations
  src/registry/memory.rs
  src/registry/persistent.rs
Labels: enhancement

#68 Fix persistent writing function
  src/registry/persistent.rs
Labels: fix

#67 Create test for the registry
  Cargo.lock
  Cargo.toml
  src/registry.rs
  src/registry/memory.rs
  src/registry/persistent.rs
Labels: documentation, enhancement

#69 Make `file_graph` function always return the first and last lines
  src/repository.rs
Labels: enhancement, fix

#70 Adding a function to StackVec to check if it is full
  src/stack.rs
Labels: enhancement

#72 Make ChangeContent implement `single_id` method
  src/change.rs
Labels: enhancement

#73 Implement generating Changes to update an SVG
  src/repository.rs
Labels: enhancement

#74 Implement the generation of changes to transform a repository to match a FileGraph
  src/repository.rs
Labels: enhancement

#75 Correctly handle replaced changes and avoid incorrect head marking
  src/repository/persistent.rs
Labels: fix

#76 Make FIRST and LAST line parent/child always the same
  src/repository.rs
Labels: enhancement

#78 Make FileGraph generation better
  src/repository.rs
Labels: enhancement

#81 Update fjall to 2.2.0
  Cargo.lock
  Cargo.toml
Labels: enhancement

#82 Remove clippy lint that make the code less readable
  Cargo.toml
Labels: enhancement

#83 Making ContentHash implement PartialOrd and Ord
  src/registry.rs
Labels: enhancement

#80 Create a structure for the final rendered file
  Cargo.lock
  Cargo.toml
  src/change.rs
  src/repository.rs
Labels: enhancement

#84 Populate LinearFile identifiers from an other LinearFile using the patience diff algorithm
  Cargo.lock
  Cargo.toml
  src/repository.rs
Labels: enhancement

#88 Implement parsing identifiers from String
  src/change.rs
  src/registry.rs
  src/repository.rs
Labels: enhancement

#89 Make all expect reason start with lowercase
  src/change.rs
  src/registry.rs
  src/repository.rs
  src/stack.rs
Labels: enhancement

#90 Separate the project into multiple crates
  Cargo.lock
  Cargo.toml
  crates/core/Cargo.toml
  crates/core/src/change.rs
  crates/core/src/lib.rs
  crates/core/src/registry.rs
  crates/core/src/repository.rs
  crates/memory/Cargo.toml
  crates/memory/src/lib.rs
  crates/memory/src/registry.rs
  crates/persistent/Cargo.toml
  crates/persistent/src/lib.rs
  crates/persistent/src/registry.rs
  crates/persistent/src/repository.rs
  crates/stack/Cargo.toml
  crates/stack/src/lib.rs
  crates/stack/src/vec.rs
Labels: enhancement
